/**
 * Core Application Constants & Enums
 * Education Department Liaquatabad Town Centre (DMC)
 */

export const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  DDO: 'DDO',
  SUPERVISOR: 'SUPERVISOR',
  HM: 'HM',
  ASSISTANT_HM: 'ASSISTANT_HM',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
});

export const SCOPES = Object.freeze({
  GLOBAL: 'GLOBAL',
  TOWN: 'TOWN',
  ASSIGNED_SCHOOLS: 'ASSIGNED_SCHOOLS',
  SCHOOL: 'SCHOOL',
  CLASS_SECTION: 'CLASS_SECTION',
  SELF_CHILD: 'SELF_CHILD',
});

export const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  REQUIRES_CORRECTION: 'REQUIRES_CORRECTION',
  SUSPENDED: 'SUSPENDED',
  TRANSFERRED: 'TRANSFERRED',
  RETIRED: 'RETIRED',
  INACTIVE: 'INACTIVE',
});

export const STUDENT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  REQUIRES_CORRECTION: 'REQUIRES_CORRECTION',
  TRANSFERRED: 'TRANSFERRED',
  GRADUATED: 'GRADUATED',
  DROPPED_OUT: 'DROPPED_OUT',
  INACTIVE: 'INACTIVE',
});

export const TEACHER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  REQUIRES_CORRECTION: 'REQUIRES_CORRECTION',
  TRANSFERRED: 'TRANSFERRED',
  RETIRED: 'RETIRED',
  SUSPENDED: 'SUSPENDED',
  INACTIVE: 'INACTIVE',
});

export const ATTENDANCE_STATUS = Object.freeze({
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LEAVE: 'LEAVE',
  LATE: 'LATE',
});

export const TRANSFER_STATUS = Object.freeze({
  INITIATED: 'INITIATED',
  AWAITING_DESTINATION_HM: 'AWAITING_DESTINATION_HM',
  JOINING_APPROVED: 'JOINING_APPROVED',
  REJECTED_BY_HM: 'REJECTED_BY_HM',
  OVERRIDDEN_AND_TRANSFERRED: 'OVERRIDDEN_AND_TRANSFERRED',
  CANCELLED: 'CANCELLED',
});

export const DOCUMENT_TYPES = Object.freeze({
  NOTICE: 'NOTICE',
  CIRCULAR: 'CIRCULAR',
  MEETING_NOTIFICATION: 'MEETING_NOTIFICATION',
  OFFICIAL_ORDER: 'OFFICIAL_ORDER',
  SYLLABUS: 'SYLLABUS',
  PDF_BOOK: 'PDF_BOOK',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
});

export const AUDIENCE_TYPES = Object.freeze({
  ALL: 'ALL',
  GOVERNMENT_OFFICERS: 'GOVERNMENT_OFFICERS',
  HM: 'HM',
  TEACHERS: 'TEACHERS',
  STUDENTS: 'STUDENTS',
  PARENTS: 'PARENTS',
});
