import mongoose from 'mongoose';
import { STUDENT_STATUS } from '../../config/constants.js';

const StudentProfileSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true, index: true },
  schoolId: { type: mongoose.Schema.Types.ObjectId, ref: 'School', required: true, index: true },
  classId: { type: mongoose.Schema.Types.ObjectId, ref: 'Class', required: true, index: true },
  sectionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Section', required: true, index: true },

  // ─── Dual Student Numbering System ───────────────────────────────────────────

  /**
   * GR No (General Register Number)
   * School-scoped sequential identity number.
   * - New Admission: auto-generated (lastGrNumber + 1), shown to HM as suggestion
   * - Old/Existing Entry: HM manually inputs the original GR from school records
   * - Unique constraint: enforced per school (schoolId + grNumber compound index)
   * - NOT shown on student-facing registration form — assigned by HM only
   */
  grNumber: {
    type: Number,
    required: true,
  },

  /**
   * Global Student ID
   * Platform-wide unique identifier. Auto-generated by system. Never editable.
   * Format: {schoolCode}-{NNNN} e.g. 'MMHA-0001', 'MMHA-0127'
   * schoolCode is set by authorized roles (HM, Supervisor, Admin+)
   */
  globalStudentId: {
    type: String,
    unique: true,
    sparse: true, // null until schoolCode is configured for the school
    trim: true,
    uppercase: true,
    index: true,
  },

  /**
   * Admission type — distinguishes new students from retrospective data entry
   */
  admissionType: {
    type: String,
    enum: ['NEW_ADMISSION', 'EXISTING_ENTRY'],
    default: 'NEW_ADMISSION',
    required: true,
  },

  // ─── Personal & Academic Info ─────────────────────────────────────────────
  dateOfBirth: { type: Date },
  gender: { type: String, enum: ['MALE', 'FEMALE', 'OTHER'] },

  fatherOrGuardianName: { type: String, required: true, trim: true },
  guardianContactNumber: { type: String, required: true },
  parentUserId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },

  residentialAddress: { type: String, default: '' },
  admissionDate: { type: Date, default: Date.now },

  lifecycleStatus: {
    type: String,
    enum: Object.values(STUDENT_STATUS),
    default: STUDENT_STATUS.PENDING_APPROVAL,
    index: true,
  },

  // ─── Enrollment Metadata ──────────────────────────────────────────────────
  enrolledBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null }, // HM who enrolled
  enrolledAt: { type: Date, default: Date.now },

}, { timestamps: true });

// ─── Indexes ──────────────────────────────────────────────────────────────────

/**
 * Core uniqueness: Within one school, no two students can share the same GR No.
 * This is enforced at the DB layer — not just application layer.
 */
StudentProfileSchema.index({ schoolId: 1, grNumber: 1 }, { unique: true });

/**
 * Class roster index: efficient queries for class/section student lists
 */
StudentProfileSchema.index({ schoolId: 1, classId: 1, sectionId: 1 });

export default mongoose.models.StudentProfile || mongoose.model('StudentProfile', StudentProfileSchema);
